# Generated by Django 3.2.8 on 2023-11-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetshopInfo2', '0002_auto_20231106_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='prénom',
        ),
        migrations.AddField(
            model_name='pets',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='pets',
            name='digital',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='pets',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pets',
            name='name',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='pets',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
