# Generated by Django 3.2.8 on 2023-11-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetshopInfo2', '0003_auto_20231106_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='digital',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='pets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
