# Generated by Django 3.2.8 on 2023-11-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetshopInfo2', '0004_auto_20231109_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='sold',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
