# Generated by Django 3.2.8 on 2023-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetshopInfo2', '0005_pets_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='sold',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3, null=True),
        ),
    ]
