# Generated by Django 3.2.8 on 2023-11-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetshopInfo2', '0007_auto_20231109_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='location',
            field=models.CharField(choices=[('Location1', 'Location 1'), ('Location2', 'Location 2'), ('Location3', 'Location 3'), ('Location4', 'Location 4')], default='Location 1', max_length=40, null=True),
        ),
    ]
