# Generated by Django 3.2.8 on 2023-11-09 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetshopInfo2', '0009_alter_pets_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='name',
            field=models.CharField(max_length=220, null=True, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[a-zA-Z ]*$')]),
        ),
    ]
