# Generated by Django 3.2.8 on 2023-11-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetshopInfo2', '0010_alter_pets_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
