# Generated by Django 3.2.8 on 2023-11-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetshopInfo2', '0011_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='digital',
        ),
    ]
